name: flutter_blue
description:
  Flutter plugin for connecting and communicating with Bluetooth Low Energy devices,
  on Android and iOS
<<<<<<< HEAD
version: 0.6.3+1
=======
version: 0.7.2
>>>>>>> upstream/master
author: Paul DeMarco <paulmdemarco@gmail.com>
homepage: https://github.com/pauldemarco/flutter_blue

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.6 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  convert: "^2.1.1"
<<<<<<< HEAD
  protobuf: "^1.0.0"
  rxdart: ^0.23.1
=======
  protobuf: "^1.0.1"
  rxdart: ^0.24.0
>>>>>>> upstream/master

dev_dependencies:
  flutter_test:
    sdk: flutter
<<<<<<< HEAD
=======
  e2e: ^0.2.1
  flutter_driver:
    sdk: flutter
>>>>>>> upstream/master

flutter:
  plugin:
    androidPackage: com.pauldemarco.flutter_blue
    pluginClass: FlutterBluePlugin
